package com.rylesolutions.flightforecast;
    import java.util.ArrayList;
    import java.util.List;

    import android.content.ContentValues;
    import android.content.Context;
    import android.database.Cursor;
    import android.database.sqlite.SQLiteDatabase;
    import android.database.sqlite.SQLiteOpenHelper;

public class DatabaseHandler extends SQLiteOpenHelper {

    private static final String DB_NAME = "airports";
    private static final int DB_VERSION = 1;

    public DatabaseHandler(Context context) {
        super(context, DB_NAME, null, DB_VERSION);

    }


    @Override
    public void onCreate(SQLiteDatabase db) {

        updateMyDatabase(db, 0, DB_VERSION);
    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {

        updateMyDatabase(db, oldVersion, newVersion);
    }

    private void updateMyDatabase(SQLiteDatabase db, int oldVersion, int newVersion) {

        if(oldVersion < 1) {
            db.execSQL("CREATE TABLE STATES (_id INTEGER PRIMARY KEY AUTOINCREMENT, "
                    + "STATE TEXT);");
            insertState(db, "Alabama");
            insertState(db, "Alaska");
            insertState(db, "Arizona");
            insertState(db, "Arkansas");
            insertState(db, "California");
            insertState(db, "Colorado");
            insertState(db, "Connecticut");
            insertState(db, "Delaware");
            insertState(db, "District of Columbia");
            insertState(db, "Florida");
            insertState(db, "Georgia");
            insertState(db, "Hawaii");
            insertState(db, "Idaho");
            insertState(db, "Illinois");
            insertState(db, "Indiana");
            insertState(db, "Iowa");
            insertState(db, "Kansas");
            insertState(db, "Kentucky");
            insertState(db, "Louisiana");
            insertState(db, "Maine");
            insertState(db, "Maryland");
            insertState(db, "Massachusetts");
            insertState(db, "Michigan");
            insertState(db, "Minnesota");
            insertState(db, "Mississippi");
            insertState(db, "Missouri");
            insertState(db, "Montana");
            insertState(db, "Nebraska");
            insertState(db, "Nevada");
            insertState(db, "New Hampshire");
            insertState(db, "New Jersey");
            insertState(db, "New Mexico");
            insertState(db, "New York");
            insertState(db, "North Carolina");
            insertState(db, "North Dakota");
            insertState(db, "Ohio");
            insertState(db, "Oklahoma");
            insertState(db, "Oregon");
            insertState(db, "Pennsylvania");
            insertState(db, "Rhode Island");
            insertState(db, "South Carolina");
            insertState(db, "South Dakota");
            insertState(db, "Tennessee");
            insertState(db, "Texas");
            insertState(db, "Utah");
            insertState(db, "Vermont");
            insertState(db, "Virginia");
            insertState(db, "Washington");
            insertState(db, "West Virginia");
            insertState(db, "Wisconsin");
            insertState(db, "Wyoming");
            insertState(db, "American Samoa");
            insertState(db, "Guam");
            insertState(db, "Northern Marianas");
            insertState(db, "Puerto Rico");
            insertState(db, "U.S. Virgin Islands");

            db.execSQL("CREATE TABLE CITIES (_id INTEGER PRIMARY KEY AUTOINCREMENT, "
                    + "STATE TEXT, CITY TEXT, CODE TEXT);");
            insertCity(db, "Alabama", "Birmingham (BHM)", "AL/Birmingham");
            insertCity(db, "Alabama", "Dothan (DHN)", "AL/Dothan");
            insertCity(db, "Alabama", "Huntsville (HSV)", "AL/Huntsville");
            insertCity(db, "Alabama", "Mobile (MOB)", "AL/Mobile");
            insertCity(db, "Alabama", "Montgomery (MGM)", "AL/Montgomery");
            insertCity(db, "Alaska", "Anchorage (ANC)", "AK/Anchorage");
            insertCity(db, "Alaska", "Fairbanks (FAI)", "AK/Fairbanks");
            insertCity(db, "Alaska", "Juneau (JNU)", "AK/Juneau");
            insertCity(db, "Arizona", "Bullhead City (IFP)", "AZ/Bullhead_City");
            insertCity(db, "Arizona", "Flagstaff (FLG)", "AZ/Flagstaff");
            insertCity(db, "Arizona", "Grand Canyon (GCN)", "AZ/Grand_Canyon");
            insertCity(db, "Arizona", "Mesa (IWA)", "AZ/MESA");
            insertCity(db, "Arizona", "Page (PGA)", "AZ/Page");
            insertCity(db, "Arizona", "Peach Springs (1G4)", "AZ/Peach_Springs");
            insertCity(db, "Arizona", "Phoenix (PHX)", "AZ/Phoenix");
            insertCity(db, "Arizona", "Tucson (TUS)", "AZ/Tucson");
            insertCity(db, "Arizona", "Yuma (NYL)", "AZ/Yuma");
            insertCity(db, "Arkansas", "Fayetteville (XNA)", "AR/Fayetteville");
            insertCity(db, "Arkansas", "Fort Smith (FSM)", "AR/Fort_Smith");
            insertCity(db, "Arkansas", "Little Rock (LIT)", "AR/Little_Rock");
            insertCity(db, "Arkansas", "Texarkana (TXK)", "AR/Texarkana");
            insertCity(db, "California", "Arcata (ACV)", "CA/Arcata");
            insertCity(db, "California", "Bakersfield (BFL)", "CA/Bakersfield");
            insertCity(db, "California", "Burbank (BUR)", "CA/Burbank");
            insertCity(db, "California", "Carlsbad (CRQ)", "CA/Carlsbad");
            insertCity(db, "California", "Chico (CIC)", "CA/Chico");
            insertCity(db, "California", "Crescent City(CEC)", "CA/Crescent_City");
            insertCity(db, "California", "Fresno (FAT)", "CA/Fresno");
            insertCity(db, "California", "Long Beach (LGB)", "CA/Long_Beach");
            insertCity(db, "California", "Los Angeles (LAX)", "CA/Los_Angeles");
            insertCity(db, "California", "Mammoth Lakes (MMH)", "CA/Mammoth_Lakes");
            insertCity(db, "California", "Modesto (MOD)", "CA/Modesto");
            insertCity(db, "California", "Monterey (MRY)", "CA/Monterey");
            insertCity(db, "California", "Oakland (OAK)", "CA/Oakland");
            insertCity(db, "California", "Ontario (ONT)", "CA/Ontario");
            insertCity(db, "California", "Palm Springs (PSP)", "CA/Palm_Springs");
            insertCity(db, "California", "Redding (RDD)", "CA/Redding");
            insertCity(db, "California", "Sacramento (SMF)", "CA/Sacramento");
            insertCity(db, "California", "San Diego (SAN)", "CA/San_Diego");
            insertCity(db, "California", "San Francisco (SFO)", "CA/San_Francisco");
            insertCity(db, "California", "San Jose (SJC)", "CA/San_Jose");
            insertCity(db, "California", "San Luis Obispo (SBP)", "CA/San_Luis_Obispo");
            insertCity(db, "California", "Santa Ana (SNA)", "CA/Santa_Ana");
            insertCity(db, "California", "Santa Barbara (SBA)", "CA/Santa_Barbara");
            insertCity(db, "California", "Santa Maria (SMX)", "CA/Santa_Maria");
            insertCity(db, "California", "Santa Rosa (STS)", "CA/Santa_Rosa");
            insertCity(db, "California", "Stockton (SCK)", "CA/Stockton");
            insertCity(db, "Colorado", "Aspen (ASE)", "CO/Aspen");
            insertCity(db, "Colorado", "Colorado Springs (COS)", "CO/Colorado_Springs");
            insertCity(db, "Colorado", "Denver (DEN)", "CO/Denver");
            insertCity(db, "Colorado", "Durango (DRO)", "CO/Durango");
            insertCity(db, "Colorado", "Eagle (EGE)", "CO/Eagle");
            insertCity(db, "Colorado", "Grand Junction (GJT)", "CO/Grand_Junction");
            insertCity(db, "Colorado", "Gunnison (GUC)", "CO/Gunnison");
            insertCity(db, "Colorado", "Hayden (HDN)", "CO/Hayden");
            insertCity(db, "Colorado", "Montrose (MTJ)", "CO/Montrose");
            insertCity(db, "Connecticut", "Hartford (BDL)", "CT/Hartford");
            insertCity(db, "Connecticut", "New Haven (HVN)", "CT/New_Haven");
            insertCity(db, "Delaware", "Wilmington (ILG)", "DE/Wilmington");
            insertCity(db, "District of Columbia", "D.C./Arlington (DCA)", "DC/Arlington");
            insertCity(db, "District of Columbia", "D.C./Dulles/Chantilly (IAD)", "DC/Dulles");
            insertCity(db, "Florida", "Daytona Beach (DAB)", "FL/Daytona_Beach");
            insertCity(db, "Florida", "Fort Lauderdale (FLL)", "FL/Fort_Lauderdale");
            insertCity(db, "Florida", "Fort Myers (RSW)", "FL/Fort_Myers");
            insertCity(db, "Florida", "Gainesville (GNV)", "FL/Gainesville");
            insertCity(db, "Florida", "Jacksonville (JAX)", "FL/Jacksonville");
            insertCity(db, "Florida", "Key West (EYW)", "FL/Key_West");
            insertCity(db, "Florida", "Melbourne (MLB", "FL/Melbourne");
            insertCity(db, "Florida", "Miami (MIA)", "FL/Miami");
            insertCity(db, "Florida", "Orlando (MCO)", "FL/Orlando");
            insertCity(db, "Florida", "Sanford (SFB)", "FL/Sanford");
            insertCity(db, "Florida", "Panama City Beach (ECP)", "FL/Panama_City_Beach");
            insertCity(db, "Florida", "Pensacola (PNS)", "FL/Pensacola");
            insertCity(db, "Florida", "Punta Gorda (PGD)", "FL/Punta_Gorda");
            insertCity(db, "Florida", "Sarasota/Bradenton (SRQ)", "FL/Sarasota");
            insertCity(db, "Florida", "St. Augustine (SGJ)", "FL/St_Augustine");
            insertCity(db, "Florida", "St. Petersburg/Clearwater (PIE)", "FL/St_Petersburg");
            insertCity(db, "Florida", "Tallahassee (TLH)", "FL/Tallahassee");
            insertCity(db, "Florida", "Tampa (TPA)", "FL/Tampa");
            insertCity(db, "Florida", "Valparaiso (VPS)", "FL/Valparaiso");
            insertCity(db, "Florida", "West Palm Beach (PBI)", "FL/West_Palm_Beach");
            insertCity(db, "Georgia", "Albany (ABY)", "GA/Albany");
            insertCity(db, "Georgia", "Atlanta (ATL)", "GA/Atlanta");
            insertCity(db, "Georgia", "Augusta (AGS)", "GA/Augusta");
            insertCity(db, "Georgia", "Brunswick (BQK)", "GA/Brunswick");
            insertCity(db, "Georgia", "Columbus (CSG)", "GA/Columbus");
            insertCity(db, "Georgia", "Savannah (SAV)", "GA/Savannah");
            insertCity(db, "Georgia", "Valdosta (VLD)", "GA/Valdosta");
            insertCity(db, "Hawaii", "Hilo (ITO)", "HI/Hilo");
            insertCity(db, "Hawaii", "Honolulu (HNL)", "HI/Honolulu");
            insertCity(db, "Hawaii", "Kahului (OGG)", "HI/Kahului");
            insertCity(db, "Hawaii", "Kailua/Kona (KOA)", "HI/Kailua");
            insertCity(db, "Hawaii", "Kaunakakai (MKK)", "HI/Kaunakakai");
            insertCity(db, "Hawaii", "Lanai City (LNY)", "HI/Lanai_City");
            insertCity(db, "Hawaii", "Lihue (LIH)", "HI/Lihue");
            insertCity(db, "Idaho", "Boise (BOI)", "ID/Boise");
            insertCity(db, "Idaho", "Hailey (SUN)", "ID/Hailey");
            insertCity(db, "Idaho", "Idaho Falls (IDA)", "ID/Idaho_Falls");
            insertCity(db, "Idaho", "Lewiston (LWS)", "ID/Lewiston");
            insertCity(db, "Idaho", "Pocatello/Arbon Valley (PIH)", "ID/Pocatello");
            insertCity(db, "Idaho", "Twin Falls (TWF)", "ID/Twin_Falls");
            insertCity(db, "Illinois", "Belleville (BLV)", "IL/Belleville");
            insertCity(db, "Illinois", "Bloomington/Normal (BMI)", "IL/Bloomington");
            insertCity(db, "Illinois", "Champaign/Urbana (CMI)", "IL/Champaign");
            insertCity(db, "Illinois", "Chicago (ORD)", "IL/Chicago");
            insertCity(db, "Illinois", "Chicago (MDW)", "IL/Chicago");
            insertCity(db, "Illinois", "Marion (MWA)", "IL/Marion");
            insertCity(db, "Illinois", "Moline (MLI)", "IL/Moline");
            insertCity(db, "Illinois", "Peoria (PIA)", "IL/Peoria");
            insertCity(db, "Illinois", "Quincy (UIN)", "IL/Quincy");
            insertCity(db, "Illinois", "Rockford (RFD)", "IL/Rockford");
            insertCity(db, "Illinois", "Springfield (SPI)", "IL/Springfield");
            insertCity(db, "Indiana", "Evansville (EVV)", "IN/Evansville");
            insertCity(db, "Indiana", "Fort Wayne (FWA)", "IN/Fort_Wayne");
            insertCity(db, "Indiana", "Indianapolis (IND)", "IN/Indianapolis");
            insertCity(db, "Indiana", "South Bend (SBN)", "IN/South_Bend");
            insertCity(db, "Iowa", "Cedar Rapids (CID)", "IA/Cedar_Rapids");
            insertCity(db, "Iowa", "Des Moines (DSM)", "IA/Des_Moines");
            insertCity(db, "Iowa", "Dubuque (DBQ)", "IA/Dubuque");
            insertCity(db, "Iowa", "Sioux City (SUX)", "IA/Sioux_City");
            insertCity(db, "Iowa", "Waterloo (ALO)", "IA/Waterloo");
            insertCity(db, "Kansas", "Garden City (GCK)", "KS/Garden_City");
            insertCity(db, "Kansas", "Manhattan (MHK)", "KS/Manhattan");
            insertCity(db, "Kansas", "Wichita (ICT)", "KS/Wichita");
            insertCity(db, "Kentucky", "Covington (CVG)", "KY/Covington");
            insertCity(db, "Kentucky", "Lexington (LEX)", "KY/Lexington");
            insertCity(db, "Kentucky", "Louisville (SDF)", "KY/Louisville");
            insertCity(db, "Kentucky", "Owensboro (OWB)", "KY/Owensboro");
            insertCity(db, "Kentucky", "Paducah (PAH)", "KY/Paducah");
            insertCity(db, "Louisiana", "Alexandria (AEX)", "LA/Alexandria");
            insertCity(db, "Louisiana", "Baton Rouge (BTR)", "LA/Baton_Rouge");
            insertCity(db, "Louisiana", "Lafayette (LFT)", "LA/Lafayette");
            insertCity(db, "Louisiana", "Lake Charles (LCH)", "LA/Lake_Charles");
            insertCity(db, "Louisiana", "Monroe (MLU)", "LA/Monroe");
            insertCity(db, "Louisiana", "New Orleans (MSY)", "LA/New_Orleans");
            insertCity(db, "Louisiana", "Shreveport (SHV)", "LA/Shreveport");
            insertCity(db, "Maine", "Bangor (BGR)", "ME/Bangor");
            insertCity(db, "Maine", "Bar Harbor (BHB)", "ME/Bar_Harbor");
            insertCity(db, "Maine", "Portland (PWM)", "ME/Portland");
            insertCity(db, "Maine", "Presque Isle (PQI)", "ME/Presque_Isle");
            insertCity(db, "Maine", "Rockland (RKD)", "ME/Rockland");
            insertCity(db, "Maryland", "Baltimore/Glen Burnie (BWI)", "MD/Baltimore");
            insertCity(db, "Maryland", "Salisbury (SBY)", "MD/Salisbury");
            insertCity(db, "Maryland", "Hagerstown (HGR)", "MD/Hagerstown");
            insertCity(db, "Massachusetts", "Boston (BOS)", "MA/Boston");
            insertCity(db, "Massachusetts", "Hyannis (HYA)", "MA/Hyannis");
            insertCity(db, "Massachusetts", "Nantucket (ACK)", "MA/Nantucket");
            insertCity(db, "Massachusetts", "Provincetown (PVC)", "MA/Provincetown");
            insertCity(db, "Massachusetts", "Vineyard Haven (MVY)", "MA/Vineyard_Haven");
            insertCity(db, "Massachusetts", "Worcester (ORH)", "MA/Worcester");
            insertCity(db, "Michigan", "Alpena (APN)", "MI/Alpena");
            insertCity(db, "Michigan", "Charlevoix (CVX)", "MI/Charlevoix");
            insertCity(db, "Michigan", "Detroit/Romulus (DTW)", "MI/Detroit");
            insertCity(db, "Michigan", "Escanaba (ESC)", "MI/Escanaba");
            insertCity(db, "Michigan", "Flint (FNT)", "MI/Flint");
            insertCity(db, "Michigan", "Grand Rapids (GRR)", "MI/Grand_Rapids");
            insertCity(db, "Michigan", "Hancock/Calumet (CMX)", "MI/Hancock");
            insertCity(db, "Michigan", "Iron Mountain/Kingsford (IMT)", "MI/Iron_Mountain");
            insertCity(db, "Michigan", "Kalamazoo/Battle Creek (AZO)", "MI/Kalamazoo");
            insertCity(db, "Michigan", "Lansing (LAN)", "MI/Lansing");
            insertCity(db, "Michigan", "Marquette/Gwinn (SAW)", "MI/Marquette");
            insertCity(db, "Michigan", "Muskegon (MKG)", "MI/Muskegon");
            insertCity(db, "Michigan", "Pellston (PLN)", "MI/Pellston");
            insertCity(db, "Michigan", "Saginaw (MBS)", "MI/Saginaw");
            insertCity(db, "Michigan", "Sault Ste. Marie (CIU)", "MI/Sault_Ste_Marie");
            insertCity(db, "Michigan", "Traverse City (TVC)", "MI/Traverse_City");
            insertCity(db, "Minnesota", "Bemidji (BJI)", "MN/Bemidji");
            insertCity(db, "Minnesota", "Brainerd (BRD)", "MN/Brainerd");
            insertCity(db, "Minnesota", "Duluth (DLH)", "MN/Duluth");
            insertCity(db, "Minnesota", "Hibbing (HIB)", "MN/Hibbing");
            insertCity(db, "Minnesota", "International Falls (INL)", "MN/International_Falls");
            insertCity(db, "Minnesota", "Minneapolis (MSP)", "MN/Minneapolis");
            insertCity(db, "Minnesota", "Rochester (RST)", "MN/Rochester");
            insertCity(db, "Minnesota", "St. Cloud (STC)", "MN/St_Cloud");
            insertCity(db, "Mississippi", "Columbus/West Point/Starkville (GTR)", "MS/Columbus");
            insertCity(db, "Mississippi", "Gulfport/Biloxi (GPT)", "MS/Biloxi");
            insertCity(db, "Mississippi", "Hattiesburg/Laurel (PIB)", "MS/Hattiesburg");
            insertCity(db, "Mississippi", "Jackson (JAN)", "MS/Jackson");
            insertCity(db, "Missouri", "Columbia (COU)", "MO/Columbia");
            insertCity(db, "Missouri", "Joplin (JLN)", "MO/Joplin");
            insertCity(db, "Missouri", "Kansas City (MCI)", "MO/Kansas_City");
            insertCity(db, "Missouri", "Springfield (SGF)", "MO/Springfield");
            insertCity(db, "Missouri", "St. Louis (STL)", "MO/St_Louis");
            insertCity(db, "Montana", "Billings (BIL)", "MT/Billings");
            insertCity(db, "Montana", "Bozeman (BZN)", "MT/Bozeman");
            insertCity(db, "Montana", "Butte (BTM)", "MT/Butte");
            insertCity(db, "Montana", "Great Falls (GTF)", "MT/Great_Falls");
            insertCity(db, "Montana", "Helena (HLN)", "MT/Helena");
            insertCity(db, "Montana", "Kalispell (GPI)", "MT/Kalispell");
            insertCity(db, "Montana", "Missoula (MSO)", "MT/Missoula");
            insertCity(db, "Nebraska", "Grand Island (GRI)", "NE/Grand_Island");
            insertCity(db, "Nebraska", "Kearney (EAR)", "NE/Kearney");
            insertCity(db, "Nebraska", "Lincoln (LNK)", "NE/Lincoln");
            insertCity(db, "Nebraska", "Omaha (OMA)", "NE/Omaha");
            insertCity(db, "Nebraska", "Scottsbluff (BFF)", "NE/Scottsbluff");
            insertCity(db, "Nevada", "Boulder City (BVU)", "NV/Boulder_City");
            insertCity(db, "Nevada", "Elko (EKO)", "NV/Elko");
            insertCity(db, "Nevada", "Las Vegas (LAS)", "NV/Las_Vegas");
            insertCity(db, "Nevada", "Reno (RNO)", "NV/Reno");
            insertCity(db, "New Hampshire", "Lebanon (LEB)", "NH/Lebanon");
            insertCity(db, "New Hampshire", "Manchester (MHT)", "NH/New_Hampshire");
            insertCity(db, "New Jersey", "Atlantic City (ACY)", "NJ/Atlantic_City");
            insertCity(db, "New Jersey", "Trenton (TTN)", "NJ/Trenton");
            insertCity(db, "New Jersey", "Newark (EWR)", "NJ/Newark");
            insertCity(db, "New Mexico", "Albuquerque (ABQ)", "NM/Albuquerque");
            insertCity(db, "New Mexico", "Farmington (FMN)", "NM/Farmington");
            insertCity(db, "New Mexico", "Hobbs (HOB)", "NM/Hobbs");
            insertCity(db, "New Mexico", "Roswell (ROW)", "NM/Roswell");
            insertCity(db, "New Mexico", "Santa Fe (SAF)", "NM/Santa_Fe");
            insertCity(db, "New York", "Albany (ALB)", "NY/Albany");
            insertCity(db, "New York", "Binghamton (BGM)", "NY/Binghamton");
            insertCity(db, "New York", "Buffalo (BUF)", "NY/Buffalo");
            insertCity(db, "New York", "Elmira/Corning (ELM)", "NY/Elmira");
            insertCity(db, "New York", "Islip (ISP)", "NY/Islip");
            insertCity(db, "New York", "Ithaca (ITH)", "NY/Ithaca");
            insertCity(db, "New York", "New York (JFK)", "NY/New_York");
            insertCity(db, "New York", "New York (LGA)", "NY/East_Elmhurst");
            insertCity(db, "New York", "Newburgh (SWF)", "NY/Newburgh");
            insertCity(db, "New York", "Niagara Falls (IAG)", "NY/Niagara_Falls");
            insertCity(db, "New York", "Plattsburgh (PBG)", "NY/Plattsburgh");
            insertCity(db, "New York", "Rochester (ROC)", "NY/Rochester");
            insertCity(db, "New York", "Syracuse (SYR)", "NY/Syracuse");
            insertCity(db, "New York", "Watertown (ART)", "NY/Watertown");
            insertCity(db, "New York", "White Plains (HPN)", "NY/White_Plains");
            insertCity(db, "North Carolina", "Asheville (AVL)", "NC/Asheville");
            insertCity(db, "North Carolina", "Charlotte (CLT)", "NC/Charlotte");
            insertCity(db, "North Carolina", "Fayetteville (FAY)", "NC/Fayetteville");
            insertCity(db, "North Carolina", "Greensboro (GSO)", "NC/Greensboro");
            insertCity(db, "North Carolina", "Greenville (PGV)", "NC/Greenville");
            insertCity(db, "North Carolina", "Jacksonville (OAJ)", "NC/Jacksonville");
            insertCity(db, "North Carolina", "New Bern (EWN)", "NC/New_Bern");
            insertCity(db, "North Carolina", "Raleigh (RDU)", "NC/Raleigh");
            insertCity(db, "North Carolina", "Wilmington (ILM)", "NC/Wilmington");
            insertCity(db, "North Dakota", "Bismarck (BIS)", "ND/Bismarck");
            insertCity(db, "North Dakota", "Dickinson (DIK)", "ND/Dickinson");
            insertCity(db, "North Dakota", "Fargo (FAR)", "ND/Fargo");
            insertCity(db, "North Dakota", "Grand Forks (GFK)", "ND/Grand_Forks");
            insertCity(db, "North Dakota", "Minot (MOT)", "ND/Minot");
            insertCity(db, "North Dakota", "Williston (ISN)", "ND/Williston");
            insertCity(db, "Ohio", "Akron/Canton (CAK)", "OH/Akron");
            insertCity(db, "Ohio", "Cleveland (CLE)", "OH/Cleveland");
            insertCity(db, "Ohio", "Columbus (CMH)", "OH/Columbus");
            insertCity(db, "Ohio", "Columbus (LCK)", "OH/Columbus");
            insertCity(db, "Ohio", "Dayton (DAY)", "OH/Dayton");
            insertCity(db, "Ohio", "Toledo (TOL)", "OH/Toledo");
            insertCity(db, "Ohio", "Youngstown/Warren (YNG)", "OH/Youngstown");
            insertCity(db, "Oklahoma", "Lawton (LAW)", "OK/Lawton");
            insertCity(db, "Oklahoma", "Oklahoma City (OKC)", "OK/Oklahoma_City");
            insertCity(db, "Oklahoma", "Tulsa (TUL)", "OK/Tulsa");
            insertCity(db, "Oregon", "Eugene (EUG)", "OR/Eugene");
            insertCity(db, "Oregon", "Klamath Falls (LMT)", "OR/Klamath_Falls");
            insertCity(db, "Oregon", "Medford (MFR)", "OR/Medford");
            insertCity(db, "Oregon", "North Bend (OTH)", "OR/North_Bend");
            insertCity(db, "Oregon", "Portland (PDX)", "OR/Portland");
            insertCity(db, "Oregon", "Redmond (RDM)", "OR/Redmond");
            insertCity(db, "Pennsylvania", "Allentown (ABE)", "PA/Allentown");
            insertCity(db, "Pennsylvania", "Erie (ERI)", "PA/Erie");
            insertCity(db, "Pennsylvania", "Harrisburg/Middletown (MDT)", "PA/Harrisburg");
            insertCity(db, "Pennsylvania", "Latrobe (LBE)", "PA/Latrobe");
            insertCity(db, "Pennsylvania", "Philadelphia (PHL)", "PA/Philadelphia");
            insertCity(db, "Pennsylvania", "Pittsburgh (PIT)", "PA/Pittsburgh");
            insertCity(db, "Pennsylvania", "State College (UNV)", "PA/State_College");
            insertCity(db, "Pennsylvania", "Wilkes-Barre/Scranton (AVP)", "PA_Scranton");
            insertCity(db, "Pennsylvania", "Williamsport (IPT)", "PA/Williamsport");
            insertCity(db, "Rhode Island", "Providence/Warwick (PVD)", "RI/Providence");
            insertCity(db, "Rhode Island", "Westerly (WST)", "RI/Westerly");
            insertCity(db, "South Carolina", "Charleston (CHS)", "SC/Charleston");
            insertCity(db, "South Carolina", "Columbia (CAE)", "SC/Columbia");
            insertCity(db, "South Carolina", "Florence (FLO)", "SC/Florence");
            insertCity(db, "South Carolina", "Greer (GSP)", "SC/Greer");
            insertCity(db, "South Carolina", "Hilton Head Island (HXD)", "SC/Hilton_Head_Island");
            insertCity(db, "South Carolina", "Myrtle Beach (MYR)", "SC/Myrtle_Beach");
            insertCity(db, "South Dakota", "Aberdeen (ABR)", "SD/Aberdeen");
            insertCity(db, "South Dakota", "Pierre (PIR)", "SD/Pierre");
            insertCity(db, "South Dakota", "Rapid City (RAP)", "SD/Rapid_City");
            insertCity(db, "South Dakota", "Sioux Falls (FSD)", "SD/Sioux_Falls");
            insertCity(db, "Tennessee", "Bristol/Johnson City/Kingsport (TRI)", "TN/Bristol");
            insertCity(db, "Tennessee", "Chattanooga (CHA)", "TN/Chattanooga");
            insertCity(db, "Tennessee", "Knoxville (TYS)", "TN/Knoxville");
            insertCity(db, "Tennessee", "Memphis (MEM)", "TN/Memphis");
            insertCity(db, "Tennessee", "Nashville (BNA)", "TN/Nashville");
            insertCity(db, "Texas", "Abilene (ABI)", "TX/Abilene");
            insertCity(db, "Texas", "Amarillo (AMA)", "TX/Amarillo");
            insertCity(db, "Texas", "Austin (AUS)", "TX/Austin");
            insertCity(db, "Texas", "Beaumont/Port Arthur (BPT)", "TX/Beaumont");
            insertCity(db, "Texas", "Brownsville (BRO)", "TX/Brownsville");
            insertCity(db, "Texas", "College Station (CLL)", "TX/College_Station");
            insertCity(db, "Texas", "Corpus Christi/Kingsville (CRP)", "TX/Corpus_Christi");
            insertCity(db, "Texas", "Dallas (DAL)", "TX/Dallas");
            insertCity(db, "Texas", "Dallas-Fort Worth (DFW)", "TX/Fort_Worth");
            insertCity(db, "Texas", "Del Rio (DRT)", "TX/Del_Rio");
            insertCity(db, "Texas", "El Paso (ELP)", "TX/El_Paso");
            insertCity(db, "Texas", "Fort Hood/Killeen/Temple (GRK)", "TX/Fort_Hood");
            insertCity(db, "Texas", "Harlingen (HRL)", "TX/Harlingen");
            insertCity(db, "Texas", "Houston (IAH)", "TX/Houston");
            insertCity(db, "Texas", "Houston (HOU)", "TX/Houston");
            insertCity(db, "Texas", "Laredo (LRD)", "TX/Laredo");
            insertCity(db, "Texas", "Longview (GGG)", "TX/Longview");
            insertCity(db, "Texas", "Lubbock (LBB)", "TX/Lubbock");
            insertCity(db, "Texas", "McAllen (MFE)", "TX/McAllen");
            insertCity(db, "Texas", "Midland (MAF)", "TX/Midland");
            insertCity(db, "Texas", "San Angelo (SJT)", "TX/San_Angelo");
            insertCity(db, "Texas", "San Antonio (SAT)", "TX/San_Antonio");
            insertCity(db, "Texas", "Tyler (TYR)", "TX/Tyler");
            insertCity(db, "Texas", "Waco (ACT)", "TX/Waco");
            insertCity(db, "Texas", "Wichita Falls (SPS)", "TX/Wichita_Falls");
            insertCity(db, "Utah", "Provo (PVU)", "UT/Provo");
            insertCity(db, "Utah", "Salt Lake City (SLC)", "UT/Salt_Lake_City");
            insertCity(db, "Utah", "St. George/Beaver (SGU)", "UT/St_George");
            insertCity(db, "Utah", "Wendover (ENV)", "UT/Wendover");
            insertCity(db, "Vermont", "Burlington (BTV)", "VT/Burlington");
            insertCity(db, "Virginia", "Charlottesville (CHO)", "VA/Charlottesville");
            insertCity(db, "Virginia", "Lynchburg (LYH)", "VA/Lynchburg");
            insertCity(db, "Virginia", "Newport News (PHF)", "VA/Newport_News");
            insertCity(db, "Virginia", "Norfolk (ORF)", "VA/Norfolk");
            insertCity(db, "Virginia", "Richmond (RIC)", "VA/Richmond");
            insertCity(db, "Virginia", "Roanoke (ROA)", "VA/Roanoke");
            insertCity(db, "Virginia", "Staunton/Waynesboro/Harrisonburg (SHD)", "VA/Staunton");
            insertCity(db, "Washington", "Bellingham (BLI)", "WA/Bellingham");
            insertCity(db, "Washington", "Friday Harbor (FHR)", "WA/Friday_Harbor");
            insertCity(db, "Washington", "Pasco (PSC)", "WA/Pasco");
            insertCity(db, "Washington", "Port Angeles (CLM)", "WA/Port_Angeles");
            insertCity(db, "Washington", "Pullman/Moscow/Idaho (PUW)", "WA/Pullman");
            insertCity(db, "Washington", "Seattle (BFI)", "WA/Seattle");
            insertCity(db, "Washington", "Seattle/Tacoma (SEA)", "WA/Tacoma");
            insertCity(db, "Washington", "Spokane (GEG)", "WA/Spokane");
            insertCity(db, "Washington", "Walla Walla (ALW)", "WA/Walla_Walla");
            insertCity(db, "Washington", "Wenatchee (EAT)", "WA/Wenatchee");
            insertCity(db, "Washington", "Yakima (YKM)", "WA/Yakima");
            insertCity(db, "West Virginia", "Charleston (CRW)", "WV/Charleston");
            insertCity(db, "West Virginia", "Clarksburg (CKB)", "WV/Clarksburg");
            insertCity(db, "West Virginia", "Huntington (HTS)", "WV/Huntington");
            insertCity(db, "West Virginia", "Lewisburg (LWB)", "WV/Lewisburg");
            insertCity(db, "West Virginia", "Morgantown (MGW)", "WV/Morgantown");
            insertCity(db, "Wisconsin", "Appleton (ATW)", "WI/Appleton");
            insertCity(db, "Wisconsin", "Eau Claire (EAU)", "WI/Eau_Claire");
            insertCity(db, "Wisconsin", "Green Bay (GRB)", "WI/Green_Bay");
            insertCity(db, "Wisconsin", "La Crosse (LSE)", "WI/La_Crosse");
            insertCity(db, "Wisconsin", "Madison (MSN)", "WI/Madison");
            insertCity(db, "Wisconsin", "Milwaukee (MKE)", "WI/Milwaukee");
            insertCity(db, "Wisconsin", "Rhinelander (RHI)", "WI/Rhinelander");
            insertCity(db, "Wisconsin", "Wausau (CWA)", "WI/Wausau");
            insertCity(db, "Wyoming", "Casper (CPR)", "WY/Casper");
            insertCity(db, "Wyoming", "Cheyenne (CYS)", "WY/Cheyenne");
            insertCity(db, "Wyoming", "Cody (COD)", "WY/Cody");
            insertCity(db, "Wyoming", "Gillette (GCC)", "WY/Gillette");
            insertCity(db, "Wyoming", "Jackson (JAC)", "WY/Jackson");
            insertCity(db, "Wyoming", "Laramie (LAR)", "WY/Laramie");
            insertCity(db, "Wyoming", "Riverton (RIW)", "WY/Riverton");
            insertCity(db, "Wyoming", "Rock Springs (RKS)", "WY/Rock_Springs");
            insertCity(db, "Wyoming", "Sheridan (SHR)", "WY/Sheridan");
            insertCity(db, "American Samoa", "Pago Pago, Tutuila (PPG)", "AS/Pago_Pago");
            insertCity(db, "Guam", "Agana/Tamuning (GUM)", "GU/Agana");
            insertCity(db, "Northern Marianas", "Obyan, Saipan Island (GSN)", "MP/Saipan_Island");
            insertCity(db, "Northern Marianas", "Rota Island (GRO)", "MP/Rota");
            insertCity(db, "Puerto Rico", "Aguadilla (BQN)", "PR/Aguadilla");
            insertCity(db, "Puerto Rico", "Ponce (PSE)", "PR/Ponce");
            insertCity(db, "Puerto Rico", "San Juan/Carolina (SJU)", "PR/Carolina");
            insertCity(db, "Puerto Rico", "San Juan/Miramar (SIG)", "PR/Miramar");
            insertCity(db, "Puerto Rico", "Vieques (VQS)", "PR/Vieques");
            insertCity(db, "U.S. Virgin Islands", "Charlotte Amalie, St. Thomas (STT)",
                    "VI/Charlotte_Amalie");
            insertCity(db, "U.S. Virgin Islands", "Christiansted, St. Croix (STX)",
                    "VI/Christiansted");
        }
    }

    public static void insertState(SQLiteDatabase db, String state) {

        ContentValues values = new ContentValues();
        values.put("STATE", state);

        db.insert("STATES", null, values);
    }

    public static void insertCity(SQLiteDatabase db, String state, String city, String code) {

        ContentValues values = new ContentValues();
        values.put("STATE", state);
        values.put("CITY", city);
        values.put("CODE", code);

        db.insert("CITIES", null, values);
    }
}
